/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user.questions;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author jasmin
 */
public class Questions extends javax.swing.JInternalFrame {

    /**
     * Creates new form Questions
     */
    public static String std;
    public static String sem;
    public static String sub;
    int curr=1;
    int cnt=0;
    ResultSet res;
    public Questions() {
        initComponents();
        
        try {
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost/online_test","root","");
            PreparedStatement prel=c.prepareStatement("select * from question where stdd=? and semm=? and subb=? ");
            prel.setString(1, std);
            prel.setString(2,sem);
            prel.setString(3, sub);
            res=prel.executeQuery();
            res.next();
            txtquelbl.setText("Question "+curr+":");
            txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    boolean check()
    {
        try {
            if(res.getString("ans").equals("a"))
            {
                if(opt1.isSelected())
                {
    
                    return true;
                }
            }
            else if(res.getString("ans").equals("b")){
                 if(opt2.isSelected())
                {
                  
                    return true;
                }
            }
            else if(res.getString("ans").equals("c")){
                if(opt3.isSelected())
                {
                   
                    return true;
                }
            }
            else {
                if(opt4.isSelected())
                {
                   
                    return true;
                }
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        txtquelbl = new javax.swing.JLabel();
        txtquestion = new javax.swing.JLabel();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        btnnxt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(334, 320));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(334, 320));

        txtquelbl.setBackground(new java.awt.Color(255, 51, 51));
        txtquelbl.setText("Question 1:");

        txtquestion.setText("jLabel2");

        opt1.setBackground(new java.awt.Color(255, 51, 51));
        opt1.setText("Answer1");

        opt2.setBackground(new java.awt.Color(255, 51, 51));
        opt2.setText("jRadioButton2");

        opt3.setBackground(new java.awt.Color(255, 51, 51));
        opt3.setText("jRadioButton3");

        opt4.setBackground(new java.awt.Color(255, 51, 51));
        opt4.setText("jRadioButton4");

        btnnxt.setText("NEXT");
        btnnxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnxtActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("A.");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("B.");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("C.");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel4.setText("D.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnnxt)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtquelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opt2)
                            .addComponent(opt1)
                            .addComponent(opt3)
                            .addComponent(opt4)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtquelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquestion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt2)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt3)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt4)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(btnnxt)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnxtActionPerformed
        // TODO add your handling code here:
        curr++;
        
        if(check()){
                    
                  cnt++;
        }
        
            
            
            if(curr==2){
               try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            } 
            }
            else if(curr==3){
                try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(curr==4){
                try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(curr==5){
                try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(curr==6){
                try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(curr==7){
                try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(curr==8){
                try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(curr==9){
                try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else if(curr==10){
                try {
                res.next();
                txtquelbl.setText("Question "+curr+":");
                txtquestion.setText(res.getString("que"));
                opt1.setText(res.getString("opta"));
                opt2.setText(res.getString("optb"));
                opt3.setText(res.getString("optc"));
                opt4.setText(res.getString("optd"));
                btnnxt.setText("Result");
                
            } catch (SQLException ex) {
                Logger.getLogger(Questions.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else{
                       JOptionPane.showMessageDialog(null,"Your Result Is "+cnt); 
                        }
            
        
    }//GEN-LAST:event_btnnxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnnxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JLabel txtquelbl;
    private javax.swing.JLabel txtquestion;
    // End of variables declaration//GEN-END:variables
}
